### ISSUE TITLE
Hanzo Menu: Navigation Links

### ISSUE THREAD

**Issue by zooqueen** [hanzoai/web#10]
The menu needs to be linked up according to [this document](https://docs.google.com/document/d/1eHgo6b_3OfWr1j1qC7VEvCOG8YDG9tbkvNpTxZYCprk/edit?usp=sharing)
<img width="925" alt="Untitled 2" src="https://github.com/hanzoai/web/assets/98129351/db782940-f06e-4326-bb6c-c070094bbf6e">

**Comment by TopTech126** [comment]
Not yet, this feature is on the header by node_module. will fix later.
