### ISSUE TITLE
Homepage: Spelling

### ISSUE THREAD

**Issue by zooqueen** [hanzoai/web#13]
This probably needs to be changed on mobile and desktop, the desktop version is shown below 

just need to make sure complex is spelled correctly

![83742a6d8de9d6bde9a5a2813cbd3ad8cd38df75cb5062357a9f344e2b7c6ec4](https://github.com/hanzoai/web/assets/98129351/400c29ef-9915-43c9-8f15-dfc578406aee)

**Comment by TopTech126** [comment]
already done
