### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by zooqueen** [hanzoai/web#14]
This probably needs to be changed on mobile and desktop, the desktop version is shown below 

These need to be underscore, only first letter should be capitalized

![2d3c472d23a4686d465df0bce95d9fe1fd6b5f945a829c3589a359cb37bc0584](https://github.com/hanzoai/web/assets/98129351/61af5ebe-8a82-48d0-94e6-990a95ba02a8)
![d149e78173b1f543eadb98db3e0367344b452efe9a5ed167e8a8119237411fd4](https://github.com/hanzoai/web/assets/98129351/01419603-1f99-4f01-ae34-974def0812e4)

**Comment by TopTech126** [comment]
done
