### ISSUE TITLE
Email popup

### ISSUE THREAD

**Issue by zooqueen** [hanzoai/web#19]
If someone clicks info@hanzo.ai towards the footer an email with to: info@hanzo.ai (autofilled) from the logged in email  on the users device, the same thing should happen if they click "get in touch" 
<img width="1498" alt="Untitled 2" src="https://github.com/hanzoai/web/assets/98129351/b5d9a49f-762c-4c31-9e24-7a910abbd64d">

**Comment by TopTech126** [comment]
This is on the header too. So, will be fix later.
