### ISSUE TITLE
Hanzo Menu: Ask AI

### ISSUE THREAD

**Issue by zooqueen** [hanzoai/web#8]
-remove the ask ai in this expanded view, and Make the font for "ask AI Chat" less bolded 

![IMG_3805](https://github.com/hanzoai/web/assets/98129351/320421d3-e1a4-4f53-851e-0e3eba294dd5)

On the expanded view of Hanzo Ai, if someone wants to "ask AI" then add prompts below

<img width="337" alt="Untitled 2" src="https://github.com/hanzoai/web/assets/98129351/4545e752-d4c6-4653-a118-3ef65c24460a">

<img width="977" alt="Untitled 2" src="https://github.com/hanzoai/web/assets/98129351/5b65a360-ff7c-43e7-be84-508057c41a2b">

**Comment by TopTech126** [comment]
This feature is on the node_module too, So I will modify this later.
